kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn assembly:assembly
  - java -jar target/calc-1.0-SNAPSHOT-jar-with-dependencies.jar
- name: docker
  image: plugins/docker 
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: calculator
    tags: latest